---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: plex
  name: plex
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      run: plex
  template:
    metadata:
      labels:
        run: plex
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - env:
        - name: TZ
          value: America/New_York
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        image: lscr.io/linuxserver/plex
        name: plex
        ports:
        - containerPort: 32400
          name: webui
          protocol: TCP
        volumeMounts: 
        - mountPath: /config 
          name: htpc-home
          subPath: plex
        - mountPath: /tv
          name: htpc-media-tv
        - mountPath: /movies
          name: htpc-media-movies
        - mountPath: /sports
          name: htpc-media-sports
        - mountPath: /music
          name: htpc-media-music
