---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: jellyplex-watched
  name: jellyplex-watched
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jellyplex-watched
  template:
    metadata:
      labels:
        run: jellyplex-watched
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - envFrom:
          - configMapRef:
              name: jellyplex-watched
        env:
          - name: PLEX_BASEURL
            valueFrom:
              secretKeyRef:
                name: jellyplex-watched
                key: plex_baseurl
          - name: PLEX_TOKEN
            valueFrom:
              secretKeyRef:
                name: jellyplex-watched
                key: plex_token
          - name: JELLYFIN_BASEURL
            valueFrom:
              secretKeyRef:
                name: jellyplex-watched
                key: jellyfin_baseurl
          - name: JELLYFIN_TOKEN
            valueFrom:
              secretKeyRef:
                name: jellyplex-watched
                key: jellyfin_token
        image: luigi311/jellyplex-watched
        name: jellyplex-watched