---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: opensprinklercontroller
  labels:
    kubernetes.io/service-name: opensprinklercontroller
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - "10.0.1.199"
    conditions: {}