apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: htpc

commonLabels:
  app: htpc

resources:
- namespace.yaml
- radarr
- sonarr
# - lidarr
- slskd
# - soularr
- bazarr
- prowlarr
# - transmission
- ingress-middlewares.yaml
- ingress-route.yaml
- nzbget
- jellyfin
- overseerr
- qbittorrent
- plex
- jellyplex-watched
- scraparr

patchesStrategicMerge:
- volumes_patch.yaml
- env_variables_patch.yaml

vars:
  - name: SONARR
    objref:
      kind: Service
      name: sonarr
      apiVersion: v1
  - name: RADARR
    objref:
      kind: Service
      name: radarr
      apiVersion: v1
  - name: PROWLARR
    objref:
      kind: Service
      name: prowlarr
      apiVersion: v1
  - name: NZBGET
    objref:
      kind: Service
      name: nzbget
      apiVersion: v1
  - name: QBITTORRENT
    objref:
      kind: Service
      name: qbittorrent
      apiVersion: v1
