# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: transmission
# spec:
#   template:
#     spec:
#       volumes: 
#       - hostPath: 
#           path: /opt/htpc 
#           type: DirectoryOrCreate 
#         name: htpc-home
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  template:
    spec:
      volumes: 
      - hostPath: 
          path: /opt/htpc 
          type: DirectoryOrCreate 
        name: htpc-home
      - hostPath: 
          path: /media/seagate
        name: htpc-media-movies
      - hostPath: 
          path: /media/seagate/plex/leaving-soon
        name: htpc-media-leaving-soon
      - hostPath: 
          path: /media/seagate2/incoming
        name: htpc-media-incoming
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  template:
    spec:
      volumes: 
      - hostPath: 
          path: /opt/htpc 
          type: DirectoryOrCreate 
        name: htpc-home
      - hostPath: 
          path: /media/seagate2
        name: htpc-media-tv
      - hostPath: 
          path: /media/seagate/plex/leaving-soon
        name: htpc-media-leaving-soon
      - hostPath: 
          path: /media/seagate2/incoming
        name: htpc-media-incoming
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
spec:
  template:
    spec:
      volumes: 
      - hostPath: 
          path: /opt/htpc 
          type: DirectoryOrCreate 
        name: htpc-home
      - hostPath: 
          path: /media/seagate2
        name: htpc-media-tv
      - hostPath:
          path: /media/seagate
        name: htpc-media-movies
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  template:
    spec:
      volumes:
      - hostPath:
          path: /opt/htpc
          type: DirectoryOrCreate
        name: htpc-home
      - hostPath: 
          path: /media/seagate2
        name: htpc-media-tv
      - hostPath:
          path: /media/seagate
        name: htpc-media-movies
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
spec:
  template:
    spec:
      volumes:
      - hostPath:
          path: /opt/htpc
          type: DirectoryOrCreate
        name: htpc-home
      - hostPath: 
          path: /media/seagate2
        name: htpc-media-tv
      - hostPath: 
          path: /media/seagate
        name: htpc-media-movies
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  template:
    spec:
      volumes:
      - hostPath:
          path: /opt/htpc/jellyfin
          type: DirectoryOrCreate
        name: jellyfin-home
      - hostPath: 
          path: /media/seagate2
        name: htpc-media-tv
      - hostPath:
          path: /media/seagate
        name: htpc-media-movies
      - hostPath:
          path: /media/seagate/plex/movies
        name: htpc-media-moviess
      - hostPath:
          path: /media/seagate2/plex/tv
        name: htpc-media-tvv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
spec:
  template:
    spec:
      volumes:
      - hostPath:
          path: /opt/htpc
          type: DirectoryOrCreate
        name: htpc-home
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  template:
    spec:
      volumes:
      - hostPath:
          path: /opt/htpc
          type: DirectoryOrCreate
        name: htpc-home
      - hostPath: 
          path: /media/seagate2/incoming
        name: htpc-media-incoming
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  template:
    spec:
      volumes:
      - hostPath:
          path: /opt/htpc
          type: DirectoryOrCreate
        name: htpc-home
      - hostPath: 
          path: /media/seagate2
        name: htpc-media-tv
      - hostPath:
          path: /media/seagate
        name: htpc-media-movies
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraparr
spec:
  template:
    spec:
      volumes:
      - hostPath:
          path: /opt/htpc
          type: DirectoryOrCreate
        name: htpc-home
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: janitorr
spec:
  template:
    spec:
      volumes:
      - hostPath:
          path: /opt/htpc/janitorr/config
          type: DirectoryOrCreate
        name: janitorr-config
      - hostPath:
          path: /opt/htpc/janitorr/logs
          type: DirectoryOrCreate
        name: janitorr-logs
      - hostPath: 
          path: /media/seagate2
        name: htpc-media-tv
      - hostPath:
          path: /media/seagate
        name: htpc-media-movies
      - hostPath: 
          path: /media/seagate/plex/leaving-soon
        name: htpc-media-leaving-soon
      - hostPath: 
          path: /media/seagate/plex
        name: htpc-media
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileflows
spec:
  template:
    spec:
      volumes:
      - hostPath:
          path: /opt/htpc/fileflows
          type: DirectoryOrCreate
        name: fileflows-home
      - hostPath: 
          path: /media/seagate2/plex/tv
        name: htpc-media-tv
      - hostPath: 
          path: /media/seagate/plex/movies
        name: htpc-media-movies
