apiVersion: v1
kind: Service
metadata:
  name: slskd
spec:
  ports:
  - port: 5030
    protocol: TCP
    targetPort: 5030
    name: webui
  - port: 50300
    protocol: TCP
    targetPort: 50300
    name: network
  selector:
    run: slskd
