apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: monitoring
spec:
  namespace: argocd
  writeBackConfig:
    method: "git:secret:argocd-image-updater-system/git-creds"
    gitConfig:
      writeBackTarget: "kustomization"
  applicationRefs:
    - namePattern: "monitoring"
      commonUpdateSettings:
        updateStrategy: "digest"
      images:
        - alias: "grafana"
          imageName: "grafana/grafana:latest"
        - alias: "prometheus"
          imageName: "prom/prometheus:latest"
        - alias: "speedtest"
          imageName: "ghcr.io/librespeed/speedtest:latest"
