apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: postgres
spec:
  namespace: argocd
  writeBackConfig:
    method: "git:secret:argocd-image-updater-system/git-creds"
    gitConfig:
      writeBackTarget: "kustomization"
  applicationRefs:
    - namePattern: "postgres"
      commonUpdateSettings:
        updateStrategy: "digest"
      images:
        - alias: "postgres"
          imageName: "postgres"
