apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: wg-easy
spec:
  namespace: argocd
  writeBackConfig:
    method: "git:secret:argocd-image-updater-system/git-creds"
    gitConfig:
      writeBackTarget: "kustomization"
  applicationRefs:
    - namePattern: "wg-easy"
      commonUpdateSettings:
        updateStrategy: "digest"
      images:
        - alias: "wg-easy"
          imageName: "ghcr.io/wg-easy/wg-easy:latest"
