apiVersion: v1
kind: Service
metadata:
  name: wg-easy
spec:
  ports:
  - port: 51820
    protocol: UDP
    targetPort: wg
    name: wg
  - port: 51821
    protocol: TCP
    targetPort: http
    name: http
  selector:
    run: wg-easy
