---
# Source: frigate/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-frigate
  namespace: default
  labels:
    app.kubernetes.io/name: frigate
    helm.sh/chart: frigate-7.8.0
    app.kubernetes.io/instance: home
    app.kubernetes.io/managed-by: Helm
data:
  config.yml: |
    mqtt:
      # Required: host name
      host: mqtt.nuc.lan
      # Optional: port (default: shown below)
      port: 1883
      # Optional: topic prefix (default: shown below)
      # WARNING: must be unique if you are running multiple instances
      topic_prefix: frigate
      # Optional: client id (default: shown below)
      # WARNING: must be unique if you are running multiple instances
      client_id: frigate
      # Optional: user
      user: '{FRIGATE_MQTT_USER}'
      # Optional: password
      # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
      #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
      password: '{FRIGATE_MQTT_PASSWORD}'
      # Optional: interval in seconds for publishing stats (default: shown below)
      stats_interval: 60
    
    detectors:
      # coral:
      #   type: edgetpu
      #   device: usb
      ov:
        type: openvino
        device: GPU
    
    model:
      width: 300
      height: 300
      input_tensor: nhwc
      input_pixel_format: bgr
      path: /openvino-model/ssdlite_mobilenet_v2.xml
      labelmap_path: /openvino-model/coco_91cl_bkgr.txt
      
    go2rtc:
      streams:
        driveway:
          - "ffmpeg:http://driveway.cams.lan/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_GO2RTC_RTSP_USERNAME}&password={FRIGATE_GO2RTC_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
        driveway_sub:
          - "ffmpeg:http://driveway.cams.lan/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_GO2RTC_RTSP_USERNAME}&password={FRIGATE_GO2RTC_RTSP_PASSWORD}"
        parking:
          - "ffmpeg:http://parking.cams.lan/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_GO2RTC_RTSP_USERNAME}&password={FRIGATE_GO2RTC_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
        parking_sub:
          - "ffmpeg:http://parking.cams.lan/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_GO2RTC_RTSP_USERNAME}&password={FRIGATE_GO2RTC_RTSP_PASSWORD}"
        backyard:
          - "ffmpeg:http://backyard.cams.lan/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_GO2RTC_RTSP_USERNAME}&password={FRIGATE_GO2RTC_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
        backyard_sub:
          - "ffmpeg:http://backyard.cams.lan/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_GO2RTC_RTSP_USERNAME}&password={FRIGATE_GO2RTC_RTSP_PASSWORD}"
        garage:
          - "ffmpeg:http://garage.cams.lan/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_GO2RTC_RTSP_USERNAME}&password={FRIGATE_GO2RTC_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
        garage_sub:
          - "ffmpeg:http://garage.cams.lan/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_GO2RTC_RTSP_USERNAME}&password={FRIGATE_GO2RTC_RTSP_PASSWORD}"
        street:
          - "ffmpeg:http://street.cams.lan/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_GO2RTC_RTSP_USERNAME}&password={FRIGATE_GO2RTC_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
        street_sub:
          - "ffmpeg:http://street.cams.lan/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_GO2RTC_RTSP_USERNAME}&password={FRIGATE_GO2RTC_RTSP_PASSWORD}"
        front_doorbell:
          - "ffmpeg:http://front-doorbell.cams.lan/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_GO2RTC_RTSP_USERNAME}&password={FRIGATE_GO2RTC_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
        front_doorbell_sub:
          - "ffmpeg:http://front-doorbell.cams.lan/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_GO2RTC_RTSP_USERNAME}&password={FRIGATE_GO2RTC_RTSP_PASSWORD}"
    
    cameras:
      # Name of your camera
      driveway:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/driveway
              roles:
                - record
            - path: rtsp://127.0.0.1:8554/driveway_sub
              roles:
                - detect
        webui_url: http://driveway.cams.lan
      parking:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/parking
              roles:
                - record
            - path: rtsp://127.0.0.1:8554/parking_sub
              roles:
                - detect
        webui_url: http://parking.cams.lan
      backyard:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/backyard
              roles:
                - record
            - path: rtsp://127.0.0.1:8554/backyard_sub
              roles:
                - detect
        webui_url: http://backyard.cams.lan
      garage:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/garage
              roles:
                - record
            - path: rtsp://127.0.0.1:8554/garage_sub
              roles:
                - detect
        webui_url: http://garage.cams.lan
      street:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/street
              roles:
                - record
            - path: rtsp://127.0.0.1:8554/street_sub
              roles:
                - detect
        webui_url: http://street.cams.lan
      front_doorbell:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/front_doorbell
              roles:
                - record
            - path: rtsp://127.0.0.1:8554/front_doorbell_sub
              roles:
                - detect
        webui_url: http://front-doorbell.cams.lan
    
    record:
      enabled: True
      retain:
        days: 1
        mode: motion
      alerts:
        retain:
          days: 2
          mode: motion
      detections:
        retain:
          days: 2
          mode: motion
---
# Source: frigate/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: home-frigate
  labels:
    app.kubernetes.io/name: frigate
    helm.sh/chart: frigate-7.8.0
    app.kubernetes.io/instance: home
    app.kubernetes.io/version: "stable"
spec:
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: http

    - name: http-auth
      port: 8971
      protocol: TCP
      targetPort: http-auth
    - name: rtmp
      port: 1935
      protocol: TCP
      targetPort: rtmp

    - name: rtsp
      port: 8554
      protocol: TCP
      targetPort: rtsp
      
    - name: webrtc-tcp
      port: 8555
      protocol: TCP
      targetPort: webrtc-tcp
    - name: webrtc-udp
      port: 8555
      protocol: UDP
      targetPort: webrtc-udp
  selector:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/instance: home
---
# Source: frigate/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-frigate
  labels:
    app.kubernetes.io/name: frigate
    helm.sh/chart: frigate-7.8.0
    app.kubernetes.io/instance: home
    app.kubernetes.io/version: "stable"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: frigate
      app.kubernetes.io/instance: home
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frigate
        app.kubernetes.io/instance: home
      annotations:
        checksum/configmap: cd56cb16519dd78836d23a821e84b77dce4f44e1c7ac078c46a3bcba4e2e772b
    spec:
      initContainers:
        - name: copyconfig
          image: "ghcr.io/blakeblackshear/frigate:stable"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /config.yml
              subPath: config.yml
              name: configmap
            - mountPath: /config
              name: config
          command: [ "cp" ]
          args: [ "-v", "/config.yml", "/config/config.yml" ]
      containers:
        - name: frigate
          image: "ghcr.io/blakeblackshear/frigate:stable"
          imagePullPolicy: IfNotPresent
          securityContext:
            {}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
            - name: http-auth
              containerPort: 8971
              protocol: TCP
            - name: rtmp
              containerPort: 1935
              protocol: TCP
            - name: rtsp
              containerPort: 8554
              protocol: TCP
            - name: webrtc-udp
              containerPort: 8555
              protocol: UDP
            - name: webrtc-tcp
              containerPort: 8555
              protocol: TCP
            - name: go2rtc-admin
              containerPort: 1984
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          env:
            - name: TZ
              value: "America/New_York"
          envFrom:
            - secretRef:
                name: frigate-secret-env
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data
              name: data
            - mountPath: /media
              name: media
            - name: dshm
              mountPath: /dev/shm
            - name: tmp
              mountPath: /tmp
          resources:
            limits:
              gpu.intel.com/i915: "1"
            requests:
              gpu.intel.com/i915: "1"
      volumes:
        - name: configmap
          configMap:
            name: home-frigate
        - name: data
          emptyDir: {}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - hostPath:
            path: /opt/smarthome/frigate
            type: DirectoryOrCreate
          name: config
        - hostPath:
            path: /opt/smarthome/frigate-media
            type: DirectoryOrCreate
          name: media
