---
# Source: frigate/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kouse.xyz-frigate
  namespace: default
  labels:
    app.kubernetes.io/name: frigate
    helm.sh/chart: frigate-7.8.0
    app.kubernetes.io/instance: kouse.xyz
    app.kubernetes.io/managed-by: Helm
data:
  config.yml: |
    mqtt:
      # Required: host name
      host: homeassistant
      # Optional: port (default: shown below)
      port: 1883
      # Optional: topic prefix (default: shown below)
      # WARNING: must be unique if you are running multiple instances
      topic_prefix: frigate
      # Optional: client id (default: shown below)
      # WARNING: must be unique if you are running multiple instances
      client_id: frigate
      # Optional: user
      user: '{FRIGATE_MQTT_USER}'
      # Optional: password
      # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
      #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
      password: '{FRIGATE_MQTT_PASSWORD}'
      # Optional: interval in seconds for publishing stats (default: shown below)
      stats_interval: 60
    
    detectors:
      # coral:
      #   type: edgetpu
      #   device: usb
      ov:
        type: openvino
        device: GPU
    
    model:
      width: 300
      height: 300
      input_tensor: nhwc
      input_pixel_format: bgr
      path: /openvino-model/ssdlite_mobilenet_v2.xml
      labelmap_path: /openvino-model/coco_91cl_bkgr.txt
      
    go2rtc:
      streams:
        driveway:
          - "ffmpeg:http://driveway.cams.lan/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_GO2RTC_RTSP_USERNAME}&password={FRIGATE_GO2RTC_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
        driveway_sub:
          - "ffmpeg:http://driveway.cams.lan/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_GO2RTC_RTSP_USERNAME}&password={FRIGATE_GO2RTC_RTSP_PASSWORD}"
    
    cameras:
      # Name of your camera
      driveway:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/driveway
              roles:
                - record
            - path: rtsp://127.0.0.1:8554/driveway_sub
              roles:
                - detect
        webui_url: http://driveway.cams.lan
---
# Source: frigate/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kouse.xyz-frigate
  labels:
    app.kubernetes.io/name: frigate
    helm.sh/chart: frigate-7.8.0
    app.kubernetes.io/instance: kouse.xyz
    app.kubernetes.io/version: "0.14.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: http

    - name: http-auth
      port: 8971
      protocol: TCP
      targetPort: http-auth
    - name: rtmp
      port: 1935
      protocol: TCP
      targetPort: rtmp

    - name: rtsp
      port: 8554
      protocol: TCP
      targetPort: rtsp
      
    - name: webrtc-tcp
      port: 8555
      protocol: TCP
      targetPort: webrtc-tcp
    - name: webrtc-udp
      port: 8555
      protocol: UDP
      targetPort: webrtc-udp
  selector:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/instance: kouse.xyz
---
# Source: frigate/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kouse.xyz-frigate
  labels:
    app.kubernetes.io/name: frigate
    helm.sh/chart: frigate-7.8.0
    app.kubernetes.io/instance: kouse.xyz
    app.kubernetes.io/version: "0.14.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: frigate
      app.kubernetes.io/instance: kouse.xyz
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frigate
        app.kubernetes.io/instance: kouse.xyz
      annotations:
        checksum/configmap: 21b47c082b9353f5b9a7c041663f8d4d68e50e0c6e8b2b531917831b483c2d5c
    spec:
      containers:
        - name: frigate
          image: "ghcr.io/blakeblackshear/frigate:0.14.1"
          imagePullPolicy: IfNotPresent
          securityContext:
            {}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
            - name: http-auth
              containerPort: 8971
              protocol: TCP
            - name: rtmp
              containerPort: 1935
              protocol: TCP
            - name: rtsp
              containerPort: 8554
              protocol: TCP
            - name: webrtc-udp
              containerPort: 8555
              protocol: UDP
            - name: webrtc-tcp
              containerPort: 8555
              protocol: TCP
            - name: go2rtc-admin
              containerPort: 1984
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          env:
            - name: TZ
              value: "America/New_York"
          envFrom:
            - secretRef:
                name: frigate-secret-env
          volumeMounts:
            - mountPath: /config/config.yml
              subPath: config.yml
              name: configmap
            - mountPath: /config
              name: config
            - mountPath: /data
              name: data
            - mountPath: /media
              name: media
            - name: dshm
              mountPath: /dev/shm
            - name: tmp
              mountPath: /tmp
          resources:
            limits:
              gpu.intel.com/i915: "1"
            requests:
              gpu.intel.com/i915: "1"
      volumes:
        - name: configmap
          configMap:
            name: kouse.xyz-frigate
        - name: config
          emptyDir: {}
        - name: data
          emptyDir: {}
        - name: media
          emptyDir: {}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
