---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: matrix
spec:
  entryPoints:
    - web
    - websecure
    - matrixfed
  routes:
  - kind: Rule
    match: Host(`matrix.kouse.xyz`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: continuwuity
      namespace: matrix
      port: 6167
  - kind: Rule
    match: Host(`matrix-webhook.kouse.xyz`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: continuwuity
      namespace: matrix
      port: hookshot-hook
  tls:
    certResolver: default
    domains:
      - main: "kouse.xyz"
        sans:
          - "*.kouse.xyz"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mautrix-wsproxy
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`matrixws.kouse.xyz`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: mautrix-wsproxy
      namespace: matrix
      port: 29331
  tls:
    certResolver: default
    domains:
      - main: "kouse.xyz"
        sans:
          - "*.kouse.xyz"
   