---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: matrix
spec:
  entryPoints:
    - matrixFederation
  routes:
  - kind: Rule
    match: Host(`matrix.kouse.xyz`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: continuwuity
      namespace: matrix
      port: 6167
  tls:
    certResolver: default
   