apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: matrix

commonLabels:
  app: matrix

resources:
- namespace.yaml
- hookshot
- continuwuity
- ingress-route.yaml
- mautrix-wsproxy

patchesStrategicMerge:
- volumes_patch.yaml