apiVersion: apps/v1
kind: Deployment
metadata:
  name: continuwuity
spec:
  template:
    spec:
      volumes: 
      - hostPath: 
          path: /opt/matrix 
          type: DirectoryOrCreate 
        name: matrix-home