apiVersion: batch/v1
kind: CronJob
metadata:
  name: security-camera-poster-update
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: security-camera-snaps
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; cd /config; find .
            volumeMounts: 
            - mountPath: /config 
              name: smarthome-home
              subPath: homeassistant
          restartPolicy: OnFailure
          volumes: 
          - hostPath: 
              path: /opt/smarthome 
              type: DirectoryOrCreate 
            name: smarthome-home