---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: smarthome
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - kind: Rule
    match: Host(`ha.kouse.xyz`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: homeassistant
      namespace: "smarthome"
      port: 8123
  tls:
    certResolver: default
    domains:
      - main: "kouse.xyz"
        sans:
          - "*.kouse.xyz"
   