---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: smarthome
spec:
  entryPoints: []
  routes:
  - kind: Rule
    match: Host(`ha.kouse.xyz`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: homeassistant
      namespace: "smarthome"
      port: 8123