---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: smarthome
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - kind: Rule
    match: Host(`ha.kouse.xyz`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: homeassistant
      namespace: "smarthome"
      port: 8123
  - kind: Rule
    match: Host(`frigate.kouse.xyz`) && ClientIP(`10.0.0.0/8`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: home-frigate
      namespace: "smarthome"
      port: http
  tls:
    certResolver: default
    domains:
      - main: "kouse.xyz"
        sans:
          - "*.kouse.xyz"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mosquitto
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: HostSNI(`mqtt.nuc.lan`)
    middlewares: []
    priority: 0
    services:
    - name: mosquitto
      namespace: smarthome
      port: mosquitto