apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smarthome

commonLabels:
  app: smarthome

resources:
- namespace.yaml
- mosquitto
- homeassistant
- frigate
- opensprinkler
- zwave
- ingress-route.yaml
# - cron.yaml

patchesStrategicMerge:
- volumes_patch.yaml