apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
spec:
  template:
    spec:
      volumes: 
      - hostPath: 
          path: /opt/smarthome 
          type: DirectoryOrCreate 
        name: smarthome-home
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  template:
    spec:
      volumes: 
      - hostPath: 
          path: /opt/smarthome/mosquitto 
          type: DirectoryOrCreate 
        name: mosquitto-home
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-frigate
spec:
  template:
    spec:
      volumes: 
      - hostPath: 
          path: /opt/smarthome/frigate 
          type: DirectoryOrCreate 
        name: config
      - hostPath: 
          path: /media/nvr
          type: DirectoryOrCreate 
        name: media
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate-echo
spec:
  template:
    spec:
      volumes: 
      - hostPath: 
          path: /opt/smarthome/frigate-echo 
          type: DirectoryOrCreate 
        name: config
      - hostPath: 
          path: /media/nvr/frigate/exports
          type: DirectoryOrCreate 
        name: exports
      - hostPath: 
          path: /media/nvr/frigate/echo_storage
          type: DirectoryOrCreate 
        name: echo_storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zwave-js-ui
spec:
  template:
    spec:
      volumes:
      - hostPath:
          path: /opt/smarthome/zwave-js-ui
          type: DirectoryOrCreate
        name: zwave-js-ui-data
      - hostPath:
          path: /dev/serial/by-id/usb-0658_0200-if00
          type: CharDevice
        name: zwavestick
