---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: unbound
spec:
  entryPoints:
    - unboundtcp
  routes:
  - match: ClientIP(`10.0.0.0/8`)
    middlewares: []
    priority: 0
    services:
    - name: unbound
      namespace: adblocker
      port: 5335
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: unbound
spec:
  entryPoints:
    - unboundudp
  routes:
  - services:
    - name: unbound
      namespace: adblocker
      port: 5335