---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: unbound
spec:
  entryPoints:
    - unboundtcp
  routes:
  - match: HostSNI(`*`)
    middlewares: []
    priority: 0
    services:
    - name: unbound
      namespace: adblocker
      port: 5335
      nativeLB: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: unbound
spec:
  entryPoints:
    - unboundudp
  routes:
  - services:
    - name: unbound
      namespace: adblocker
      port: 5335
      nativeLB: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: blocky
spec:
  entryPoints:
    - prometheus
  routes:
  - kind: Rule
    match: Host(`blocky.kouse.xyz`) && ClientIP(`10.0.0.0/8`)
    priority: 0
    services:
    - kind: Service
      name: blocky
      namespace: adblocker
      port: prometheus
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: blocky
spec:
  entryPoints:
    - dnstcp
  routes:
  - match: HostSNI(`*`)
    middlewares: []
    priority: 0
    services:
    - name: blocky
      namespace: adblocker
      port: 53
      nativeLB: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: blocky
spec:
  entryPoints:
    - dnsudp
  routes:
  - services:
    - name: blocky
      namespace: adblocker
      port: 53
      nativeLB: true