apiVersion: v1
kind: Service
metadata:
  name: zwave-js-ui
spec:
  ports:
  - port: 80
    targetPort: http
    name: http
  - port: 3000
    targetPort: websocket
    name: websocket
  selector:
    run: zwave-js-ui
