apiVersion: v1
kind: Service
metadata:
  name: unbound
spec:
  ports:
  - port: 5335
    protocol: TCP
    targetPort: 5335
    name: dns-tcp
  - port: 5335
    protocol: UDP
    targetPort: 5335
    name: dns-udp
  selector:
    run: unbound
