apiVersion: v1
kind: Service
metadata:
  name: unbound
spec:
  ports:
  - port: 53
    protocol: TCP
    targetPort: 53
    name: dns-tcp
  - port: 53
    protocol: UDP
    targetPort: 53
    name: dns-udp
  selector:
    run: homeassistant
