---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: homeassistant
  name: homeassistant
spec:
  strategy:
    type: Recreate # since using hostNetwork we can't rollout due to port constraints
  replicas: 1
  selector:
    matchLabels:
      run: homeassistant
  template:
    metadata:
      labels:
        run: homeassistant
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - env:
        - name: TZ
          value: America/New_York
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: PYTHONHTTPSVERIFY
          value: "0"
        image: lscr.io/linuxserver/homeassistant
        # resources:
        #   requests:
        #     memory: "455Mi"
        #     cpu: "36m"
        name: homeassistant
        ports:
        - containerPort: 8123
          name: webui
          protocol: TCP
        - containerPort: 6666
          name: broadcast1
          protocol: UDP
        - containerPort: 6667
          name: broadcast2
          protocol: UDP
        volumeMounts: 
        - mountPath: /config 
          name: smarthome-home
          subPath: homeassistant
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
