apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  ports:
  - port: 8123
    protocol: TCP
    targetPort: 8123
    name: webui
  - port: 5353
    protocol: UDP
    targetPort: 5353
    name: homekitdns
  - port: 21063
    protocol: TCP
    targetPort: 21063
    name: homekit
  selector:
    run: homeassistant
