apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/perfect-water
images:
  - name: ghcr.io/chadkouse/perfect-water
    digest: sha256:1c25142511ce92a0b7713523bbdec56af5ad301753173e9a6988aa5bbb907366
