apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/perfect-water
images:
  - name: ghcr.io/chadkouse/perfect-water
    digest: sha256:407e63f00c9775794c329c4bb28474b11233ed58489118c0659a503b08c5f53f
