apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/perfect-water
images:
  - name: ghcr.io/chadkouse/perfect-water
    digest: sha256:7d377c66a0963adf4a74f28ad456150a17dca8a72f3e9367998226c9b4d2362d
