apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: webui
  - port: 55881
    protocol: TCP
    targetPort: 55881
    name: torrent
  selector:
    run: qbittorrent
