---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: hookshot
  name: hookshot
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hookshot
  template:
    metadata:
      labels:
        run: hookshot
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: matrix-hookshot
        image: halfshot/matrix-hookshot
        env:
          - name: TZ
            value: America/New_York
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
        ports:
          - name: webhook
            containerPort: 9000
            protocol: TCP
          - name: metrics
            containerPort: 9001
            protocol: TCP
          - name: appservice
            containerPort: 9002
            protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: matrix-home
          subPath: matrix-hookshot