apiVersion: v1
kind: Service
metadata:
  name: hookshot
spec:
  ports:
    - port: 9000
      targetPort: webhook
      protocol: TCP
      name: webhook
    - port: 9001
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 9002
      targetPort: appservice
      protocol: TCP
      name: appservice
  selector:
    run: hookshot