apiVersion: v1
kind: Service
metadata:
  name: hookshot
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    name: hookshot-hook
  - port: 9002
    protocol: TCP
    targetPort: 9002
    name: hookshot-stat
  - port: 9993
    protocol: TCP
    targetPort: 9993
    name: hookshot
  selector:
    run: hookshot