apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
data:
  init-unifi.sh: |
    #!/bin/bash
    mongosh -u "$MONGO_INITDB_ROOT_USERNAME" -p "$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase admin <<EOF
    db.getSiblingDB("admin").createUser({
      user: "unifi",
      pwd: "$MONGO_UNIFI_PASSWORD",
      roles: [
        {role: "readWriteAnyDatabase", db: "admin"},
        {role: "dbAdminAnyDatabase", db: "admin"}
      ]
    });
    EOF
