---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: lidarr
  name: lidarr
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      run: lidarr
  template:
    metadata:
      labels:
        run: lidarr
    spec:
      securityContext:
        # runAsUser: 1000
        # runAsGroup: 1000
        fsGroup: 1000    
      initContainers:
      - name: chown
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /config && chown -R 1000:1000 /music"]
        volumeMounts:
        - mountPath: /config 
          name: htpc-home
          subPath: lidarr
        - mountPath: /music 
          name: htpc-media-music
      containers:
      - env:
        - name: TZ
          value: America/New_York
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        image: linuxserver/lidarr
        name: lidarr
        ports:
        - containerPort: 8686
          name: webui
        volumeMounts: 
        - mountPath: /config 
          name: htpc-home
          subPath: lidarr
        - mountPath: /music 
          name: htpc-media-music
        - mountPath: /incoming 
          name: htpc-media-incoming
