apiVersion: apps/v1
kind: Deployment
metadata:
  name: sillytavern
spec:
  template:
    spec:
      volumes: 
      - hostPath: 
          path: /opt/ai/models 
          type: DirectoryOrCreate 
        name: aimodels-home
      - hostPath: 
          path: /opt/ai/sillytavern 
          type: DirectoryOrCreate 
        name: sillytavern-home
