---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: openclaw
  name: openclaw
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      run: openclaw
  template:
    metadata:
      labels:
        run: openclaw
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        fsGroup: 1000
      containers:
      - name: openclaw
        image: ghcr.io/openclaw/openclaw:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: America/New_York
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: openclaw-secrets
              key: ANTHROPIC_API_KEY
        - name: OPENCLAW_CONFIG_PATH
          value: /etc/openclaw/openclaw.json
        ports:
        - containerPort: 18789
          name: web
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /data
          name: openclaw-data
        - mountPath: /etc/openclaw
          name: openclaw-config
