---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: overseerr
  name: overseerr
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      run: overseerr
  template:
    metadata:
      labels:
        run: overseerr
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - env:
        - name: TZ
          value: America/New_York
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        image: lscr.io/linuxserver/overseerr
        name: overseerr
        ports:
        - containerPort: 5055
          name: webui
          protocol: TCP
        volumeMounts: 
        - mountPath: /config 
          name: htpc-home
          subPath: jellyfin
