---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: continuwuity
  name: continuwuity
spec:
  replicas: 1
  selector:
    matchLabels:
      run: continuwuity
  template:
    metadata:
      labels:
        run: continuwuity
    spec:
      strategy:
        type: Recreate # since using hostNetwork we can't rollout due to port constraints
      securityContext:
        fsGroup: 1000
      containers:
      - envFrom:
          - configMapRef:
              name: continuwuity
        env:
          - name: TZ
            value: America/New_York
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: CONTINUWUITY_SERVER_NAME
            valueFrom:
              secretKeyRef:
                key: CONTINUWUITY_SERVER_NAME
                name: matrix
          - name: CONTINUWUITY_REGISTRATION_TOKEN
            valueFrom:
              secretKeyRef:
                key: CONTINUWUITY_REGISTRATION_TOKEN
                name: matrix
          - name: CONTINUWUITY_TURN_SECRET
            valueFrom:
              secretKeyRef:
                key: CONTINUWUITY_TURN_SECRET
                name: matrix
        image: forgejo.ellis.link/continuwuation/continuwuity
        name: continuwuity
        ports:
        - containerPort: 6167
          name: webui
          protocol: TCP
        volumeMounts: 
        - mountPath: /var/lib/continuwuity 
          name: continuwuity-home
      initContainers:
      - name: mautrix-whatsapp
        image: dock.mau.dev/mautrix/whatsapp
        restartPolicy: Always
        command: ["/usr/bin/mautrix-whatsapp"]
        args: ["-c", "/data/config.yaml", "--no-update"]
        env:
          - name: TZ
            value: America/New_York
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
        ports:
        - containerPort: 29318
          name: mautrix-wa
          protocol: TCP
        volumeMounts: 
        - mountPath: /data 
          name: matrix-home
          subPath: mautrix-whatsapp
      - name: mautrix-slack
        image: dock.mau.dev/mautrix/slack
        restartPolicy: Always
        command: ["/usr/bin/mautrix-slack"]
        args: ["-c", "/data/config.yaml", "--no-update"]
        env:
          - name: TZ
            value: America/New_York
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
        ports:
        - containerPort: 29335
          name: mautrix-slack
          protocol: TCP
        volumeMounts: 
        - mountPath: /data 
          name: matrix-home
          subPath: mautrix-slack
