---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: continuwuity
  name: continuwuity
spec:
  replicas: 1
  selector:
    matchLabels:
      run: continuwuity
  template:
    metadata:
      labels:
        run: continuwuity
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - env:
        - name: TZ
          value: America/New_York
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        image: forgejo.ellis.link/continuwuation/continuwuity
        name: continuwuity
        ports:
        - containerPort: 6167
          name: webui
          protocol: TCP
        volumeMounts: 
        - mountPath: /var/lib/continuwuity 
          name: matrix-home
          subPath: continuwuity