apiVersion: v1
kind: Service
metadata:
  name: continuwuity
spec:
  ports:
  - port: 6167
    protocol: TCP
    targetPort: 6167
    name: webui
  - port: 29318
    protocol: TCP
    targetPort: 29318
    name: mautrix-wa
  - port: 29335
    protocol: TCP
    targetPort: 29335
    name: mautrix-slack
  - port: 9000
    protocol: TCP
    targetPort: 9000
    name: hookshot-hook
  - port: 9993
    protocol: TCP
    targetPort: 9993
    name: hookshot
  selector:
    run: continuwuity