apiVersion: v1
kind: Service
metadata:
  name: continuwuity
spec:
  ports:
  - port: 6167
    protocol: TCP
    targetPort: 6167
    name: webui
  - port: 29318
    protocol: TCP
    targetPort: 29318
    name: mautrix-whatsapp
  selector:
    run: continuwuity