apiVersion: v1
kind: ConfigMap
metadata:
  name: coturn
data:
  CONTINUWUITY_DATABASE_PATH: "/var/lib/continuwuity"
  CONTINUWUITY_PORT: "6167" # should match the loadbalancer traefik label
  CONTINUWUITY_MAX_REQUEST_SIZE: "20000000" # in bytes, ~20 MB
  CONTINUWUITY_ALLOW_REGISTRATION: 'true'
  CONTINUWUITY_ALLOW_FEDERATION: 'true'
  CONTINUWUITY_ALLOW_CHECK_FOR_UPDATES: 'true'
  CONTINUWUITY_TRUSTED_SERVERS: '["matrix.org"]'
  CONTINUWUITY_ADDRESS: "0.0.0.0"