---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: coturn
  name: coturn
spec:
  replicas: 1
  selector:
    matchLabels:
      run: coturn
  template:
    metadata:
      labels:
        run: coturn
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - envFrom:
          - configMapRef:
              name: coturn
        env:
          - name: TZ
            value: America/New_York
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: CONTINUWUITY_SERVER_NAME
            valueFrom:
              secretKeyRef:
                key: CONTINUWUITY_SERVER_NAME
                name: matrix
          - name: CONTINUWUITY_REGISTRATION_TOKEN
            valueFrom:
              secretKeyRef:
                key: CONTINUWUITY_REGISTRATION_TOKEN
                name: matrix
        image: coturn/coturn
        name: coturn
        ports:
        - containerPort: 3478
          hostPort: 3478
          name: turn-port1
          protocol: UDP
        - containerPort: 3478
          hostPort: 3478
          name: turn-port2
          protocol: TCP
        volumeMounts: 
        - mountPath: /var/lib/coturn 
          name: coturn-home
          subPath: data
        - mountPath: /etc/coturn 
          name: coturn-home
          subPath: config
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet