apiVersion: v1
kind: Service
metadata:
  name: coturn
spec:
  selector:
    run: coturn
  type: ClusterIP
  ports:
    - port: 3478
      targetPort: 3478
      protocol: UDP
      name: turn-port1
    - port: 3478
      targetPort: 3478
      protocol: TCP
      name: turn-port2