---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: jellyplex-watched
  name: jellyplex-watched
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jellyplex-watched
  template:
    metadata:
      labels:
        run: jellyplex-watched
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: touch
        image: busybox
        command: ["sh", "-c", "touch /config/.env"]
        volumeMounts:
        - mountPath: /config
          name: smarthome-home
          subPath: jellyplex-watched
      containers:
      - env:
        - name: TZ
          value: America/New_York
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        image: luigi311/jellyplex-watched
        name: jellyplex-watched
        volumeMounts: 
        - mountPath: /config 
          name: smarthome-home
          subPath: jellyplex-watched
      hostNetwork: true