apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openclaw

commonLabels:
  app: openclaw

resources:
- namespace.yaml
- openclaw
- ingress-route.yaml

patchesStrategicMerge:
- volumes_patch.yaml
