apiVersion: v1
kind: Service
metadata:
  name: blocky
spec:
  ports:
  - port: 53
    protocol: TCP
    targetPort: 53
    name: blocky-tcp
  - port: 53
    protocol: UDP
    targetPort: 53
    name: blocky-udp
  - port: 4001
    protocol: TCP
    targetPort: blocky-stats
    name: blocky-stats
  selector:
    run: blocky