apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base/adblocker

resources:
- application.yaml

images:
  - name: mvance/unbound
    newTag: latest
  - name: spx01/blocky
    newTag: v0.26.2
